### ISSUE TITLE
未能启动cfnat ，openwrt是arm不是x86 是不是这个原因啊？

### ISSUE THREAD

**Issue by loadnl** [PoemMistyMoon/cfnat-openwrt#1]
openwrt CPU是ARMv8 Processor x 4
请选择一个选项 [0-8]:
1
主程序和必要文件已存在，跳过下载
LAN 口的 IPv4 地址: 100.64.2.151
正在读取配置文件...
没有找到运行中的 cfnat 进程跳过本操作
未能启动cfnat或获取PID，检查进程。

**Comment by PoemMisty** [comment]
应该不是结构的问题，虽然我懒，但我也做了arm64的适配，启动后如果提示失败，使用`ps | grep '[c]fnat'`这个命令，查看是否有./cfnat,程序在运行，如果有那就是程序获取不到pid，但还能运行，没有影响，如果没有，再回复我

**Comment by loadnl** [comment]
ps | grep '[c]fnat' 没有显示内容，应该是没运行，我自己看你的脚本里面 去安装目录/root/cfnatop下面 是没有对应的文件的，不知道是什么原因

**Comment by PoemMisty** [comment]
> ps | grep '[c]fnat' 没有显示内容，应该是没运行，我自己看你的脚本里面 去安装目录/root/cfnatop下面 是没有对应的文件的，不知道是什么原因

那我知道原因了，你的本地网络连不上github，下载其实是失败了，但是我没写下载失败的检测代码，你可以把root/cfnatop文件夹内容全删了，挂代理下载，载完之后关闭代理的代理本机功能，稍后我修改一下代码，加上镜像地址和下载失败检测

**Comment by loadnl** [comment]
嗯嗯 ，应该是你说的这样 多谢了 我自己手动复制进去 可以运行了
