### ISSUE TITLE
指定数据中心没效果

### ISSUE THREAD

**Issue by ssd2077** [PoemMistyMoon/cfnat-openwrt#2]
奠信宽带

openwrt 23.05  (ImmortalWrt)

指定数据中心为SJC，实际连接到NRT（走日本NTT，超高丢包）

**Comment by PoemMistyMoon** [comment]
这应该是程序本身的问题，我写这个脚本只是拼接了启动参数，因为这个程序本身不开源，我也没办法修改，这个应该是原作者频道，你可以下载最新的程序替换试试https://t.me/CF_NAT

**Comment by PoemMisty** [comment]
> 奠信宽带
> 
> openwrt 23.05 (ImmortalWrt)
> 
> 指定数据中心为SJC，实际连接到NRT（走日本NTT，超高丢包）

这应该是程序本身的问题，我写这个脚本只是拼接了启动参数，因为这个程序本身不开源，我也没办法修改，这个应该是原作者频道，你可以下载最新的程序替换试试https://t.me/CF_NAT

**Comment by PoemMisty** [comment]
> 奠信宽带
> 
> openwrt 23.05 (ImmortalWrt)
> 
> 指定数据中心为SJC，实际连接到NRT（走日本NTT，超高丢包）

试试这个脚本能否正常使用，cm加入了colo，

`bash <(curl -Ls https://raw.cmliussss.com/cfnat.sh)`

**Comment by ssd2077** [comment]
> > 奠信宽带
> > openwrt 23.05 (ImmortalWrt)
> > 指定数据中心为SJC，实际连接到NRT（走日本NTT，超高丢包）
> 
> 试试这个脚本能否正常使用，cm加入了colo，
> 
> `bash <(curl -Ls https://raw.cmliussss.com/cfnat.sh)`

这个脚本正常。不过提示/dev/fd/64: line 839: stty: command not found。看着有点膈应。
